# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-05-10 11:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20190510_1416'),
    ]

    operations = [
        migrations.RenameField(
            model_name='location',
            old_name='name',
            new_name='location',
        ),
    ]
